/// `#[Value("${key:default}")]` proc_macro_attribute — field-level annotation.
///
/// This macro is a **helper attribute** only — it is a no-op passthrough.
/// The real injection logic is generated by `#[Component]` (component_impl),
/// which scans for `#[Value(...)]` on fields and emits env-read statements
/// inside the bean's supplier closure.
///
/// Example usage:
/// ```ignore
/// #[Component]
/// #[derive(Debug, Default, Clone)]
/// struct Config {
///     #[Value("${server.port:8080}")]
///     port: i32,
///     #[Value("${app.name:rust-spring}")]
///     name: String,
/// }
/// ```
use proc_macro::TokenStream;

#[allow(dead_code)]
pub fn value_impl(_attribute: TokenStream, item: TokenStream) -> TokenStream {
    item // passthrough — real logic is in component_impl
}
